#!/bin/bash

# Bash script to parse repair results generated by Astor
# Astor simply outputs all generated repairs as 'diff' files
# This script quickly parses the output folder to generate numbers of variants and solutions for each package

# Log Output Path

# Initialize counters
VARIANTS=0
SOLUTIONS=0

VARIANTS=$(find ./output_astor/AstorMain-calculator/bin/ -type d -name "variant*" | wc -l)
SOLUTIONS=$(find ./output_astor/AstorMain-calculator/src/ -type d -name "variant*_f" | wc -l)
echo 'jgenprog','calc',50,$VARIANTS,$SOLUTIONS